name: CI Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --immutable
        working-directory: .

      - name: Lint
        run: yarn lint
        working-directory: .

      - name: TypeScript compilation
        run: yarn tsc
        working-directory: .

      - name: Run tests
        run: yarn test
        working-directory: .

  build-android:
    runs-on: ubuntu-latest
    container:
      image: reactnativecommunity/react-native-android

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build Android App
        run: cd android && ./gradlew assembleRelease

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          yarn install
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
      - name: Install Pods
        run: |
          cd ios && pod install
      - name: Build iOS App
        run: |
          npx react-native run-ios --no-packager

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: tavoargento/react-native-android-ci:0.0.1